version: "3.3"
services:
  gui:
    image: arssolvendi.azurecr.io/bcinab-gui:alpha5
    depends_on:
      - api
    links:
      - api
    ports:
      - 8080:80
    networks:
      - backend
      - frontend

  api:
    image: arssolvendi.azurecr.io/bcinab-api:alpha5
    volumes:
      - source: '\\.\pipe\docker_engine_windows'
        target: '\\.\pipe\docker_engine'
        type: npipe
      - source: 'C:\Windows\System32\drivers\etc\'
        target: 'c:\driversetc\'
        type: bind
      - source: 'C:\programdata\bcinab\'
        target: 'c:\programdata\bcinab\'
        type: bind
    networks:
      - backend

networks:
  frontend:
    driver: nat
  backend:
    driver: nat
